version: 0.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: false
  verbosity: minimal
after_test: 
    - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"nunit-console.exe" -targetargs:".\Toscana.Tests\bin\Debug\Toscana.Tests.dll" -hideskipped:All -output:.\Toscana_coverage.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "Toscana_coverage.xml"
deploy:
- provider: NuGet
  api_key:
    secure: 7fn0WOlE16mVKH/QyyCCU4D3bTtXKolXKNBMbLOZZmXydWKOeKxBN7ictdxCIKS+